// <auto-generated />
using System;
using MedLabAInsights.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedLabAInsights.Data.Migrations
{
    [DbContext(typeof(MedlabAinsightDbContext))]
    [Migration("20260123163935_Add_PanelRuleSummary")]
    partial class Add_PanelRuleSummary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MedLabAInsights.Models.BandRuleReport", b =>
                {
                    b.Property<int>("BandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BandCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BandName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomValue")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("RangeMax")
                        .HasColumnType("REAL");

                    b.Property<double>("RangeMin")
                        .HasColumnType("REAL");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StandardReport")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BandId");

                    b.HasIndex("TestId");

                    b.HasIndex("TestId", "BandCode")
                        .IsUnique();

                    b.ToTable("BandRuleReport", (string)null);
                });

            modelBuilder.Entity("MedLabAInsights.Models.Panel", b =>
                {
                    b.Property<int>("PanelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PanelCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PanelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PanelId");

                    b.ToTable("Panel", (string)null);
                });

            modelBuilder.Entity("MedLabAInsights.Models.PanelRuleSummary", b =>
                {
                    b.Property<int>("PanelRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSeverity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinSeverity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PanelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PanelRuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PanelRuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("PanelRuleId");

                    b.HasIndex("PanelId");

                    b.HasIndex("PanelId", "PanelRuleCode")
                        .IsUnique();

                    b.ToTable("PanelRuleSummary", (string)null);
                });

            modelBuilder.Entity("MedLabAInsights.Models.PanelTestMapping", b =>
                {
                    b.Property<int>("PanelTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportanceLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PanelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PanelTestId");

                    b.HasIndex("TestId");

                    b.HasIndex("PanelId", "TestId")
                        .IsUnique();

                    b.ToTable("PanelTestMapping", (string)null);
                });

            modelBuilder.Entity("MedLabAInsights.Models.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomValues")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinValue")
                        .HasColumnType("REAL");

                    b.Property<string>("TestCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TestId");

                    b.HasIndex("TestName")
                        .IsUnique();

                    b.ToTable("Test", (string)null);
                });

            modelBuilder.Entity("MedLabAInsights.Models.BandRuleReport", b =>
                {
                    b.HasOne("MedLabAInsights.Models.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("MedLabAInsights.Models.PanelRuleSummary", b =>
                {
                    b.HasOne("MedLabAInsights.Models.Panel", "Panel")
                        .WithMany()
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panel");
                });

            modelBuilder.Entity("MedLabAInsights.Models.PanelTestMapping", b =>
                {
                    b.HasOne("MedLabAInsights.Models.Panel", "Panel")
                        .WithMany()
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedLabAInsights.Models.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panel");

                    b.Navigation("Test");
                });
#pragma warning restore 612, 618
        }
    }
}
