// <auto-generated />
using System;
using MedLabAInsights.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedLabAInsights.Data.Migrations
{
    [DbContext(typeof(MedlabAinsightDbContext))]
    [Migration("20260123162342_Add_Panel_Test_MasterAndMappings")]
    partial class Add_Panel_Test_MasterAndMappings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MedLabAInsights.Models.Panel", b =>
                {
                    b.Property<int>("PanelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PanelCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PanelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PanelId");

                    b.ToTable("Panel", (string)null);
                });

            modelBuilder.Entity("MedLabAInsights.Models.PanelTestMapping", b =>
                {
                    b.Property<int>("PanelTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportanceLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PanelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PanelTestId");

                    b.HasIndex("TestId");

                    b.HasIndex("PanelId", "TestId")
                        .IsUnique();

                    b.ToTable("PanelTestMapping", (string)null);
                });

            modelBuilder.Entity("MedLabAInsights.Models.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomValues")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinValue")
                        .HasColumnType("REAL");

                    b.Property<string>("TestCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TestId");

                    b.HasIndex("TestName")
                        .IsUnique();

                    b.ToTable("Test", (string)null);
                });

            modelBuilder.Entity("MedLabAInsights.Models.PanelTestMapping", b =>
                {
                    b.HasOne("MedLabAInsights.Models.Panel", "Panel")
                        .WithMany()
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedLabAInsights.Models.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panel");

                    b.Navigation("Test");
                });
#pragma warning restore 612, 618
        }
    }
}
