// <auto-generated />
using System;
using MedLabAInsights.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedLabAInsights.Data.Migrations
{
    [DbContext(typeof(MedlabAinsightDbContext))]
    [Migration("20260125122702_AddVisitFlowTables")]
    partial class AddVisitFlowTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MedLabAInsights.Models.BandRuleReport", b =>
                {
                    b.Property<int>("BandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BandCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BandName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomValue")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("RangeMax")
                        .HasColumnType("REAL");

                    b.Property<double>("RangeMin")
                        .HasColumnType("REAL");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StandardReport")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BandId");

                    b.HasIndex("TestId");

                    b.HasIndex("TestId", "BandCode")
                        .IsUnique();

                    b.ToTable("BandRuleReport", (string)null);
                });

            modelBuilder.Entity("MedLabAInsights.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Contact")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("MemberId");

                    b.HasIndex("Contact")
                        .IsUnique();

                    b.ToTable("Member", (string)null);
                });

            modelBuilder.Entity("MedLabAInsights.Models.Panel", b =>
                {
                    b.Property<int>("PanelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PanelCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PanelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PanelId");

                    b.ToTable("Panel", (string)null);
                });

            modelBuilder.Entity("MedLabAInsights.Models.PanelRuleSummary", b =>
                {
                    b.Property<int>("PanelRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSeverity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinSeverity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PanelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PanelRuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PanelRuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("PanelRuleId");

                    b.HasIndex("PanelId");

                    b.HasIndex("PanelId", "PanelRuleCode")
                        .IsUnique();

                    b.ToTable("PanelRuleSummary", (string)null);
                });

            modelBuilder.Entity("MedLabAInsights.Models.PanelTestMapping", b =>
                {
                    b.Property<int>("PanelTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportanceLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PanelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PanelTestId");

                    b.HasIndex("TestId");

                    b.HasIndex("PanelId", "TestId")
                        .IsUnique();

                    b.ToTable("PanelTestMapping", (string)null);
                });

            modelBuilder.Entity("MedLabAInsights.Models.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomValues")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinValue")
                        .HasColumnType("REAL");

                    b.Property<string>("TestCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TestId");

                    b.HasIndex("TestName")
                        .IsUnique();

                    b.ToTable("Test", (string)null);
                });

            modelBuilder.Entity("MedLabAInsights.Models.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Diastolic")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PanelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Systolic")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("VisitDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("VisitId");

                    b.HasIndex("PanelId");

                    b.HasIndex("MemberId", "VisitDateTime");

                    b.ToTable("Visit", (string)null);
                });

            modelBuilder.Entity("MedLabAInsights.Models.VisitPanelSummary", b =>
                {
                    b.Property<int>("VisitPanelSummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevised")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PanelRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RevisedSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardSummarySnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VisitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VisitPanelSummaryId");

                    b.HasIndex("EvaluatedAt");

                    b.HasIndex("PanelRuleId");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("VisitPanelSummary", (string)null);
                });

            modelBuilder.Entity("MedLabAInsights.Models.VisitTestInterpretation", b =>
                {
                    b.Property<int>("VisitTestInterpretationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BandId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevised")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RevisedReport")
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardReportSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VisitTestResultId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VisitTestInterpretationId");

                    b.HasIndex("BandId");

                    b.HasIndex("EvaluatedAt");

                    b.HasIndex("VisitTestResultId")
                        .IsUnique();

                    b.ToTable("VisitTestInterpretation", (string)null);
                });

            modelBuilder.Entity("MedLabAInsights.Models.VisitTestResult", b =>
                {
                    b.Property<int>("VisitTestResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EnteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VisitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VisitTestResultId");

                    b.HasIndex("TestId");

                    b.HasIndex("VisitId", "TestId")
                        .IsUnique();

                    b.ToTable("VisitTestResult", (string)null);
                });

            modelBuilder.Entity("MedLabAInsights.Models.BandRuleReport", b =>
                {
                    b.HasOne("MedLabAInsights.Models.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("MedLabAInsights.Models.PanelRuleSummary", b =>
                {
                    b.HasOne("MedLabAInsights.Models.Panel", "Panel")
                        .WithMany()
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panel");
                });

            modelBuilder.Entity("MedLabAInsights.Models.PanelTestMapping", b =>
                {
                    b.HasOne("MedLabAInsights.Models.Panel", "Panel")
                        .WithMany()
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedLabAInsights.Models.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panel");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("MedLabAInsights.Models.Visit", b =>
                {
                    b.HasOne("MedLabAInsights.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedLabAInsights.Models.Panel", "Panel")
                        .WithMany()
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Panel");
                });

            modelBuilder.Entity("MedLabAInsights.Models.VisitPanelSummary", b =>
                {
                    b.HasOne("MedLabAInsights.Models.PanelRuleSummary", "PanelRuleSummary")
                        .WithMany()
                        .HasForeignKey("PanelRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedLabAInsights.Models.Visit", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PanelRuleSummary");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("MedLabAInsights.Models.VisitTestInterpretation", b =>
                {
                    b.HasOne("MedLabAInsights.Models.BandRuleReport", "BandRuleReport")
                        .WithMany()
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedLabAInsights.Models.VisitTestResult", "VisitTestResult")
                        .WithMany()
                        .HasForeignKey("VisitTestResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BandRuleReport");

                    b.Navigation("VisitTestResult");
                });

            modelBuilder.Entity("MedLabAInsights.Models.VisitTestResult", b =>
                {
                    b.HasOne("MedLabAInsights.Models.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedLabAInsights.Models.Visit", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("Visit");
                });
#pragma warning restore 612, 618
        }
    }
}
